Don't use parenthesized initialisation of arrays
This is a GCC extension. In C++11, the outer parentheses are not
required. Fixes compile time error using clang++:

     error: parenthesized initialization of a member array is a
          GNU extension [-Wgnu-array-member-paren-init]